# docker-compose.yml
version: "3.9"

services:
  products:
    build: ./SubgraphProducts
    ports:
      - "5000:80"

  users:
    build: ./SubgraphUsers
    ports:
      - "5001:80"

  router:
    image: ghcr.io/apollographql/router:v1.41.1
    ports:
      - "4000:4000"
    volumes:
      - ./Supergraph/supergraph.graphql:/dist/schema/supergraph.graphql
      - ./Supergraph/router-config.yaml:/dist/schema/router-config.yaml
    command: > 
      --supergraph /dist/schema/supergraph.graphql 
      --config /dist/schema/router-config.yaml
      --listen 0.0.0.0:4000
    depends_on:
      - products
      - users
