federation_version: 2
subgraphs:
  products:
    routing_url: http://products/graphql
    schema:
      file: ./products.graphql
  users:
    routing_url: http://users/graphql
    schema:
      file: ./users.graphql
